---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  minReadySeconds: 10
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: nginx
    spec: 
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80 



---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec: 
  selector:
    app: nginx
  type: NodePort
  ports:
    - nodePort: 30008
      port: 80
      targetPort: 80